spring:
  webflux:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${FILE_LOCATION:./market-app/config/static}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: PT1M
  application:
    name: my-market-app
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:my_market_db}
    username: ${DB_USER:yp_user}
    password: ${DB_PASSWORD:yp_password}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:my_market_db}
    user: ${DB_USER:yp_user}
    password: ${DB_PASSWORD:yp_password}

  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/market-app}
        registration:
          b2b:
            client-id: market-app
            client-secret: ${KEYCLOAK_CLIENT_SECRET:G8eG1ctvsrarlmgmmOtuaVlo85ey0T7k}
            authorizationGrantType: client_credentials
            scope: openid
            provider: keycloak
          keycloak:
            client-id: market-app
            client-secret: ${KEYCLOAK_CLIENT_SECRET:G8eG1ctvsrarlmgmmOtuaVlo85ey0T7k}
            authorizationGrantType: authorization_code
            scope: openid, profile, email
            provider: keycloak


server:
  port: ${APP_PORT:8081}
logging:
  level:
    ru.yandex.practicum.my_market_app: debug

payment-service:
  base-url: ${PAYMENT_SERVICE_URL:http://localhost:8090}