spring:
  webflux:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${FILE_LOCATION:./market-app/config/static}
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: PT1M
  application:
    name: my-market-app
  r2dbc:
    url: ${DB_URL:r2dbc:mysql://localhost:3306/my_market_db}
    username: ${DB_USER:yp_user}
    password: ${DB_PASSWORD:yp_password}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: ${APP_PORT:8080}
logging:
  level:
    ru.yandex.practicum.my_market_app: debug

payment-service:
  base-url: ${PAYMENT_SERVICE_URL:http://localhost:8090}