version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      # Для входа в UI будут использоваться эти параметры
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    ports:
      # В нашем случае Keycloak будет запущен на локальном порту 8080
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: mysql:oraclelinux9
    container_name: market-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: my_market_db
      MYSQL_USER: yp_user
      MYSQL_PASSWORD: yp_password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 20
  redis:
    image: redis:8.2.7-bookworm
    container_name: market-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  market-app:
    container_name: market-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./market-app/Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - ./market-app/.env
  payment-service:
    container_name: payment-service-app
    env_file:
      - ./payment-service/.env
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    ports:
      - "8090:8090"