/*
 * API Сервиса оплаты заказа
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.my_market_app.model.dto.payment;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.concurrent.atomic.AtomicLong;

/**
 * Balance
 */
@ToString
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Balance {

    private AtomicLong balance = new AtomicLong(0);

    public Balance(Long balance) {
        this.balance.set(balance);
    }

    /**
     * Get balance
     *
     * @return balance
     */
    @NotNull
    @Schema(name = "balance", example = "15000", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty("balance")
    public Long getBalance() {
        return balance.get();
    }

    @JsonProperty("balance")
    public void setBalance(Long balance) {
        this.balance.set(balance);
    }

}

