/*
 * API Сервиса оплаты заказа
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.my_market_app.model.dto.payment;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ChargeBalanceRequest
 */

@ToString
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor
@JsonTypeName("chargeBalance_request")
public class ChargeBalanceRequest {

    private Long totalSum;

    /**
     * Get totalSum
     *
     * @return totalSum
     */
    @NotNull(message = "Необходимо указать сумму для списания")
    @Min(value = 0, message = "Сумма для списания не должна быть отрицательной")
    @Schema(name = "totalSum", example = "4000", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty("totalSum")
    public Long getTotalSum() {
        return totalSum;
    }

    @JsonProperty("totalSum")
    public void setTotalSum(Long totalSum) {
        this.totalSum = totalSum;
    }

}


