/*
 * API Сервиса оплаты заказа
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.my_market_app.model.dto;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ChargeBalanceRequest
 */
@JsonPropertyOrder({
  ChargeBalanceRequest.JSON_PROPERTY_TOTAL_SUM
})
@JsonTypeName("chargeBalance_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-06T15:32:35.378501+03:00[Europe/Moscow]", comments = "Generator version: 7.22.0")
public class ChargeBalanceRequest {
  public static final String JSON_PROPERTY_TOTAL_SUM = "totalSum";
  @jakarta.annotation.Nonnull
  private Long totalSum;

  public ChargeBalanceRequest() {
  }

  public ChargeBalanceRequest totalSum(@jakarta.annotation.Nonnull Long totalSum) {
    
    this.totalSum = totalSum;
    return this;
  }

  /**
   * Get totalSum
   * @return totalSum
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL_SUM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTotalSum() {
    return totalSum;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_SUM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalSum(@jakarta.annotation.Nonnull Long totalSum) {
    this.totalSum = totalSum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargeBalanceRequest chargeBalanceRequest = (ChargeBalanceRequest) o;
    return Objects.equals(this.totalSum, chargeBalanceRequest.totalSum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalSum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargeBalanceRequest {\n");
    sb.append("    totalSum: ").append(toIndentedString(totalSum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

