/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.22.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.yadex.practicum.server.api;

import ru.yadex.practicum.server.domain.Balance;
import ru.yadex.practicum.server.domain.Error;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;


@Validated
@Tag(name = "balance", description = "the balance API")
public interface BalanceApi {

    String PATH_GET_BALANCE = "/balance";
    /**
     * GET /balance : Получение текущего баланса
     *
     * @return Возвращает текущий баланс (status code 200)
     *         or Некорректный запрос (status code 400)
     *         or Ошибки сервера (status code 5XX)
     */
    @Operation(
        operationId = "getBalance",
        summary = "Получение текущего баланса",
        responses = {
            @ApiResponse(responseCode = "200", description = "Возвращает текущий баланс", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Balance.class))
            }),
            @ApiResponse(responseCode = "400", description = "Некорректный запрос", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "5XX", description = "Ошибки сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = BalanceApi.PATH_GET_BALANCE,
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<Balance>> getBalance(
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
    
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"balance\" : 15000 }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
    
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"message\" : \"Сообщение об ошибке\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
    
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"message\" : \"Сообщение об ошибке\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
    

        return result.then(Mono.empty());

    }

}
