/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.22.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.yadex.practicum.server.api;

import ru.yadex.practicum.server.domain.ChargeBalanceRequest;
import ru.yadex.practicum.server.domain.ChargeStatus;
import ru.yadex.practicum.server.domain.Error;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-06-06T15:12:08.905819+03:00[Europe/Moscow]", comments = "Generator version: 7.22.0")
@Validated
@Tag(name = "chargeBalance", description = "the chargeBalance API")
public interface ChargeBalanceApi {

    String PATH_CHARGE_BALANCE = "/chargeBalance";
    /**
     * POST /chargeBalance : Списание суммы заказа со счета
     *
     * @param chargeBalanceRequest Сумма для списания (required)
     * @return Успешное списание средств (status code 200)
     *         or Некорректный запрос (status code 400)
     *         or Ошибки сервера (status code 5XX)
     */
    @Operation(
        operationId = "chargeBalance",
        summary = "Списание суммы заказа со счета",
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешное списание средств", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ChargeStatus.class))
            }),
            @ApiResponse(responseCode = "400", description = "Некорректный запрос", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "5XX", description = "Ошибки сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ChargeBalanceApi.PATH_CHARGE_BALANCE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<ChargeStatus>> chargeBalance(
        @Parameter(name = "ChargeBalanceRequest", description = "Сумма для списания", required = true) @Valid @RequestBody Mono<ChargeBalanceRequest> chargeBalanceRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
    
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"status\" : \"Оплата прошла успешно\", \"isSuccess\" : true }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
    
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"message\" : \"Сообщение об ошибке\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
    
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"message\" : \"Сообщение об ошибке\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
    

        return result.then(chargeBalanceRequest).then(Mono.empty());

    }

}
